apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: pure-flex
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pure_k8s_plugin.labels" . | indent 4}}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pure-flex
  template:
    metadata:
      labels:
        app: pure-flex
{{ include "pure_k8s_plugin.labels" . | indent 8}}
    spec:
{{- if (eq "openshift" .Values.orchestrator.name) }}
      nodeSelector:
        node-role.kubernetes.io/compute: "true"
{{- end}}
      serviceAccountName: {{ .Values.clusterrolebinding.serviceAccount.name }}
      containers:
        - name: pure-flex
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - >
                    touch /tmp/.uninstall_start_flag;
                    while true; do
                    if [ -f /tmp/.uninstall_finish_flag ]; then
                    exit;
                    fi;
                    sleep 1;
                    done
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          command:
            - "/pure-flex-daemon"
            - "--kubeletBaseDir=/kubelet-plugins"
{{- if eq .Values.app.debug true}}
            - "--debug"
{{- end}}
            - "--daemon"
            - "install"
          volumeMounts:
          - name: config
            mountPath: /etc/pure
          - name: kubelet-plugins
            mountPath: /kubelet-plugins
          env:
          - name: PURE_DISCOVERY_CONF
            value: /etc/pure/pure.json
          - name: PURE_FLASHARRAY_SAN_TYPE
            value: {{ .Values.flasharray.sanType | upper }}
          - name: PURE_K8S_NAMESPACE
            value: {{ .Values.namespace.pure }}
          - name: PURE_DEFAULT_BLOCK_FS_TYPE
            value: {{ .Values.flasharray.defaultFSType }}
          - name: PURE_DEFAULT_BLOCK_FS_OPT
            value: "{{ .Values.flasharray.defaultFSOpt }}"
          - name: PURE_DEFAULT_BLOCK_MNT_OPT
            value: "{{ .Values.flasharray.defaultMountOpt }}"
          - name: PURE_PREEMPT_RWO_ATTACHMENTS_DEFAULT
            value: "{{ .Values.flasharray.preemptAttachments }}"
      volumes:
        - name: config
          configMap:
            name: pure-provisioner-config
        - name: kubelet-plugins
          hostPath:
           path: {{ template "pure_k8s_plugin.flexpath" .}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
