{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: pure-provisioner-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pure_csi.labels" . | indent 4}}
data:
  pure.json: {{ .Values.arrays | toJson | b64enc | quote }}
{{- end }}
